In [7]:
import pandas as pd

In [8]:

# Cargar el dataset
file_path = '/content/drive/MyDrive/Colab Notebooks/SeminarioWeb/Reviews.csv'
df = pd.read_csv(file_path)
df.head()

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...

In [9]:
#muestra  el numero de filas y colunnas
df.shape

(568454, 10)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 568454 entries, 0 to 568453
Data columns (total 10 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Id                      568454 non-null  int64
 1   ProductId               568454 non-null  object
 2   UserId                  568454 non-null  object
 3   ProfileName             568428 non-null  object
 4   HelpfulnessNumerator    568454 non-null  int64
 5   HelpfulnessDenominator  568454 non-null  int64
 6   Score                   568454 non-null  int64
 7   Time                    568454 non-null  int64
 8   Summary                 568427 non-null  object
 9   Text                    568454 non-null  object
dtypes: int64(5), object(5)
memory usage: 43.4+ MB

In [11]:
df.describe()

,Id,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time
count,568454.000000,568454.000000,568454.00000,568454.000000,5.684540e+05
mean,284227.500000,1.743817,2.22881,4.183199,1.296257e+09
std,164098.679298,7.636513,8.28974,1.310436,4.804331e+07
min,1.000000,0.000000,0.00000,1.000000,9.393408e+08
25%,142114.250000,0.000000,0.00000,4.000000,1.271290e+09
50%,284227.500000,0.000000,1.00000,5.000000,1.311120e+09
75%,426340.750000,2.000000,2.00000,5.000000,1.332720e+09
max,568454.000000,866.000000,923.00000,5.000000,1.351210e+09

In [12]:
df.sample(10)

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
500173,500174,B0014J5RBS,A3NYVOP2ZDZL1M,K. Carone,0,0,5,1208131200,Candy Fish Order,My order was received very fast and in excelle...
330066,330067,B0002D8MBY,A267U5ACM1VWHW,AshleyMonique,2,2,5,1314144000,Great; Doesn't taste like it's from scratch bu...,I really like this marinade. My Jamaican paren...
254814,254815,B007PA32L2,A1YMQCE0GG56I6,keke,1,1,5,1327104000,yummy!,This pumpkin spice coffee is very good. Not ov...
529784,529785,B0032CB15Q,A2R62M0NK9GHLW,Chere L,0,0,5,1348963200,Yummy coffee,"I love the taste of this coffee, when it touch..."
41693,41694,B001P20FCU,A3S9VY4R8BCTKZ,M. sharp,0,0,5,1336089600,best salt,I read that the Tibetan Pink Sea Salt is the h...
387757,387758,B000FKL0D6,AYVTPIGJBOB70,James Mueller,0,0,5,1173657600,pure awesomeness,"Less expensive than a grocery store, and the t..."
428538,428539,B002R8J7YS,AI2PFU3E9OMDY,S. Kent,0,6,2,1278288000,"Beware, these are Teensy Tiny Treats",I had to give handfuls to my St. Bernard - the...
4532,4533,B002TMV3E4,A2PK64OVZA1U8Z,Jakester,0,2,5,1285891200,Exceptional coffee!,I've decaffinated a few times and always find ...
212539,212540,B002Q8JOSI,A2HPF56C5C13I1,"Nina ""nal001""",1,1,5,1296518400,Good Ingredients & the Dogs Really Like Them,Both of my dogs love these bars. They smell g...
446542,446543,B0009F3QLQ,A2EIDL9KC24KBE,Alexandra,0,0,5,1328054400,Works for PMS & cramps!,I discovered this product a couple of years ag...

In [13]:
df.isnull().sum()

Id                         0
ProductId                  0
UserId                     0
ProfileName               26
HelpfulnessNumerator       0
HelpfulnessDenominator     0
Score                      0
Time                       0
Summary                   27
Text                       0
dtype: int64

In [14]:
import pandas as pd

df['Time'] = pd.to_datetime(df['Time'], unit='s')

print(df['Time'])

0        2011-04-27
1        2012-09-07
2        2008-08-18
3        2011-06-13
4        2012-10-21
            ...
568449   2011-03-09
568450   2012-03-09
568451   2012-02-21
568452   2012-03-13
568453   2012-05-31
Name: Time, Length: 568454, dtype: datetime64[ns]

In [15]:
#elimina la data null
df = df.dropna()

In [16]:
 # Muestra df sin data null
df.isnull().sum()

Id                        0
ProductId                 0
UserId                    0
ProfileName               0
HelpfulnessNumerator      0
HelpfulnessDenominator    0
Score                     0
Time                      0
Summary                   0
Text                      0
dtype: int64

In [18]:
#Muestra los tipos de Datos
df.dtypes

Id                                 int64
ProductId                         object
UserId                            object
ProfileName                       object
HelpfulnessNumerator               int64
HelpfulnessDenominator             int64
Score                              int64
Time                      datetime64[ns]
Summary                           object
Text                              object
dtype: object

In [19]:
#Exploración inicial
print(df.shape)
print(df.info())
print(df.isnull().sum())

(568401, 10)
<class 'pandas.core.frame.DataFrame'>
Index: 568401 entries, 0 to 568453
Data columns (total 10 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Id                      568401 non-null  int64
 1   ProductId               568401 non-null  object
 2   UserId                  568401 non-null  object
 3   ProfileName             568401 non-null  object
 4   HelpfulnessNumerator    568401 non-null  int64
 5   HelpfulnessDenominator  568401 non-null  int64
 6   Score                   568401 non-null  int64
 7   Time                    568401 non-null  datetime64[ns]
 8   Summary                 568401 non-null  object
 9   Text                    568401 non-null  object
dtypes: datetime64[ns](1), int64(4), object(5)
memory usage: 47.7+ MB
None
Id                        0
ProductId                 0
UserId                    0
ProfileName               0
HelpfulnessNumerator      0
HelpfulnessDenominator    0
Score                     0
Time                      0
Summary                   0
Text                      0
dtype: int64

In [20]:
#elimina duplicadosd
f.drop_duplicates(inplace=True)

In [21]:
# Convertir timestamp a fecha
df['Time'] = pd.to_datetime(df['Time'], unit='s')

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 568401 entries, 0 to 568453
Data columns (total 10 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Id                      568401 non-null  int64
 1   ProductId               568401 non-null  object
 2   UserId                  568401 non-null  object
 3   ProfileName             568401 non-null  object
 4   HelpfulnessNumerator    568401 non-null  int64
 5   HelpfulnessDenominator  568401 non-null  int64
 6   Score                   568401 non-null  int64
 7   Time                    568401 non-null  datetime64[ns]
 8   Summary                 568401 non-null  object
 9   Text                    568401 non-null  object
dtypes: datetime64[ns](1), int64(4), object(5)
memory usage: 47.7+ MB